import { Link } from 'react-router-dom'
import { Moon, Sun } from 'lucide-react'
import { useState, useEffect } from "react"; import '../index.css'

function App() {
    const [darkMode, setDarkMode] = useState(true);

    useEffect(() => {
        document.body.className = darkMode ? "dark" : "light";
    }, [darkMode]);

    const toggleTheme = () => {
        setDarkMode(prev => !prev);
    };

    return (
        <>
            <header>
                <section id="header-left">
                    <h3>made with &lt;3 by mzums</h3>
                </section>
                <section id="header-right">
                    <a id="header-btn" href="https://github.com/mzums/fakewiki/pulls" target="_blank" rel="noreferrer">
                        contribute
                    </a>
                    <a id="header-btn" href="https://github.com/mzums/fakewiki" target="_blank" rel="noreferrer">
                        GitHub
                    </a>
                    <button
                        onClick={toggleTheme}
                        className={`icon-btn ${darkMode ? "moon" : "sun"}`}
                    >
                        {darkMode ? <Moon /> : <Sun />}
                    </button>
                </section>
            </header>
            <section id="welcome">
                <h1>Welcome to <a href="https://github.com/mzums/fakewiki">FakeWiki</a>,</h1>
                <h3>the fake encyclopedia maintained by <a href="https://mzums.com">mzums</a></h3>
                <h3>
                    Articles generated by a custom-trained AI model based on data from
                    <a href="https://en.wikipedia.org"> Wikipedia</a>.
                </h3>
                <h3>Learn more</h3>
            </section>


            <h4 id="view-all">
                view  <Link to="/All_Articles">all articles...</Link>
            </h4>

            <section id="cards">
                <section id="card-row">
                    <section id="card">
                        <section id="card-title">
                            From today's featured article
                        </section>
                        <p id="card-text">
                            The name of the computer game console and the game console is a software that combines the original system of the same name, which can be used in the computer game console. It was developed in the early 1990s by the IBM Computer Engine, and developed in 1992.

                        </p>
                    </section>

                    <section id="card">
                        <section id="card-title">
                            In the news
                        </section>
                        <p id="card-text">
                            The name of the computer game console and the game console is a software that combines the original system of the same name, which can be used in the computer game console. It was developed in the early 1990s by the IBM Computer Engine, and developed in 1992.

                        </p>
                    </section>
                </section>


                <section id="card-row">
                    <section id="card">
                        <section id="card-title">
                            Did you know ...
                        </section>
                        <p id="card-text">
                            The name of the computer game console and the game console is a software that combines the original system of the same name, which can be used in the computer game console. It was developed in the early 1990s by the IBM Computer Engine, and developed in 1992.

                        </p>
                    </section>

                    <section id="card">
                        <section id="card-title">
                            On this day
                        </section>
                        <p id="card-text">
                            The name of the computer game console and the game console is a software that combines the original system of the same name, which can be used in the computer game console. It was developed in the early 1990s by the IBM Computer Engine, and developed in 1992.

                        </p>
                    </section>
                </section>

            </section>

            <footer>
                <p>Note that all information on this page is fictional and this project was created for educational purposes only.</p>
            </footer>
        </>
    )
}

export default App