import { Link } from 'react-router-dom'
import '../index.css'

function Main_Page() {
    return (
        <>
            <div className="main-container">
                <img id="main-img" src="/fake2.png" alt="logo" />
                <section id="welcome">
                    <h1>Welcome to <a href="https://github.com/mzums/fakewiki">FakeWiki</a>,</h1>
                    <h3>the fake encyclopedia maintained by <a href="https://mzums.com">mzums</a></h3>
                    <h3>
                        Articles generated by a custom-trained AI model based on data from
                        <a href="https://en.wikipedia.org"> Wikipedia</a>.
                    </h3>
                </section>
            </div>

            <h4 id="view-all">
                view  <Link to="/All_Articles">all articles...</Link>
            </h4>

            <section id="cards">
                <section id="card-row">
                    <section id="card">
                        <section id="card-title">
                            From today's featured article
                        </section>
                        <p id="card-text">
                            The name of the computer game console and the game console is a software that combines the original system of the same name, which can be used in the computer game console. It was developed in the early 1990s by the IBM Computer Engine, and developed in 1992.
                        </p>
                    </section>

                    <section id="card">
                        <section id="card-title">
                            In the news
                        </section>
                        <p id="card-text">
                            The name of the computer game console and the game console is a software that combines the original system of the same name, which can be used in the computer game console. It was developed in the early 1990s by the IBM Computer Engine, and developed in 1992.
                        </p>
                    </section>
                </section>

                <section id="card-row">
                    <section id="card">
                        <section id="card-title">
                            Did you know ...
                        </section>
                        <p id="card-text">
                            The name of the computer game console and the game console is a software that combines the original system of the same name, which can be used in the computer game console. It was developed in the early 1990s by the IBM Computer Engine, and developed in 1992.
                        </p>
                    </section>

                    <section id="card">
                        <section id="card-title">
                            On this day
                        </section>
                        <p id="card-text">
                            The name of the computer game console and the game console is a software that combines the original system of the same name, which can be used in the computer game console. It was developed in the early 1990s by the IBM Computer Engine, and developed in 1992.
                        </p>
                    </section>
                </section>
            </section>
        </>
    )
}

export default Main_Page